### PR TITLE
added newer projects

### LINKED ISSUE #4: Addition of newer projects
There are a lot of new projects which haven't been added to the website. A few these projects are:- 

- [gyft](https://github.com/metakgp/gyft)
- [kronos](https://github.com/metakgp/Kronos)
- [Chillzone](https://github.com/metakgp/chillzone)
- [what-slot](https://github.com/metakgp/what-slot)
- [wimp](https://github.com/metakgp/wimp)
- [erp auto login](https://github.com/metakgp/erp-auto-login)

Proper cards regarding these projects should be added and linked.

### PR DESCRIPTION
**Pull request by sahil-shubham**
## Changes 
- Added newer projects. 
- Increased the number of card columns for lesser scrolling.  
- Added more info regarding metakgp to make it look fuller

## Screenshots
 
metakgp

metakgp2

### CODE REVIEW

**Comment by thealphadollar** [comment]
@sahil-shubham This is really amazing. Can you please add the following as well:

- Sarathi

Apart from this, all seems cool to me. Do you think we can also add projects which may not be functional at the moment such as Hermes, Naarad, Leprechaun, etc. Please refer to the sheet in the description of the meta-x channel.

**Comment by sahil-shubham** [comment]
Hi @thealphadollar ,this took more time than expected because of the course load :sweat_smile: .

I have added the cards for the projects which are still in development, I went through different ways to show them like adding a different section etc., but I settled with the following design: 

ss

I have added title to the anchor tags to let one know that these are in development. I like this method of including non functional projects as it is subtle and can be easily changed when the projects get deployed or ready. Let me know what you think about this approach.

**Comment by thealphadollar** [comment]
This looks really cool, thanks @sahil-shubham . I like the idea of having a tooltip with the title for non-functional projects and they can be disabled quickly in the future once we make them functional; it's really handy.

Since, @Ayushk4 was involved in the discussion, I will merge the PR once it has been approved by him since his view point is important to understand if there are any new improvements we can make here :star:

**Review by thealphadollar — APPROVED** [review]

**Comment by thealphadollar** [comment]
Thank you @sahil-shubham for the much-needed contribution towards improving the project. I think @Ayushk4 is busy with the semester and the changes look good to me, so I'll move forward and merge the same.

**Pull request merged**
