### PR TITLE
Improved design, added logo

### PR DESCRIPTION
**Pull request by xypnox**
These were the changes made:

- Added Logo
- Made header background vibrant
- Fixed some typography
- Fixed cards
- Made a better footer

The site is still mobile Friendly

### CODE REVIEW

**Review by ghostwriternr — CHANGES_REQUESTED** [review]
Hey @xypnox , thanks a lot for the PR.

I quite like the changes here. The footer in particular looks like a nice thing to have. The logo and typography changes look very nice! Just a couple of minor nitpicks though.

1. I'm not a big fan of the color change and really liked the original ones. So can you please revert that one thing?
2. The margin between the header gradient and the page title seems to be too big on mobile. Can you please reduce that to original values too?
3. The logo and footer text would both look a lot nicer in white! Converting the logo color should be a 1 minute task with something like Lunapic (online) or paint-equivalent tools on your machine.

Can you make these changes and add a commit? Thanks!

**Comment by xypnox** [comment]
I have added the changes you requested, I have reverted the color scheme and fixed the margin in mobile. Also the text of Header and Footer have been changed to white. Here is a Preview:

**Review by ghostwriternr — APPROVED** [review]
Sweet! Looks great :smile:

**Comment by ghostwriternr** [comment]
Changes should now reflect at https://metakgp.github.io/.
Thanks for the PR, @xypnox !

**Pull request merged**
