### PR TITLE
Add project cards for easier viewing

### PR DESCRIPTION
**Pull request by kaustubhhiware**
Added project cards as discussed in last meetup.
Prep for freshers intro seminar.
Once approved and suggestions made, can be squashed.
Temporarily can be tested here: http://cse.iitkgp.ac.in/~hknarendra/metakgp/

### CODE REVIEW

**Comment by icyflame** [comment]
Hey, great work!

Personally, I am not a fan of the hovering cards thing. I would prefer flat design (like in [jackal/projects](https://clenemt.github.io/jackal/projects/).

**Comment by kaustubhhiware** [comment]
I've had a look at jackal. These are not hovering cards. No modal opens when these cards are clicked, only a link to each project.

**Comment by icyflame** [comment]
No, I meant the card itself is hovering on top of the web page. i.e the shadow effect, and  the card popping up whenever you hover your mouse pointer over the card.

**Comment by kaustubhhiware** [comment]
@icyflame @ghostwriternr If there is no issue can this be merged?
If there is an improvement to be made, let me know.

**Comment by ghostwriternr** [comment]
@kaustubhhiware I have no issue with this. 

It's definitely an improvement over the current version. The projects have a more prominent place on the page now. My only suggestion would be to force the links to open in a new tab instead of the same one. It's a 2-minute fix and can be done as mentioned [here](https://stackoverflow.com/questions/17711146/how-to-open-link-in-new-tab-on-html).

Once that is done, go ahead to merge 👍 Nice work! 😄

**Comment by kaustubhhiware** [comment]
Updated. All commits can be squashed now.

**Comment by athityakumar** [comment]
@kaustubhhiware - Just saw this PR. Good work! How about adding buttons with links to their respective GitHub repositories (wherever applicable, like mfqp, mcmp and naarad)?

**Comment by kaustubhhiware** [comment]
Clicking the project title does that. Would having buttons be better ?

**Comment by athityakumar** [comment]
For example, mfqp opens https://qp.metakgp.org/ and it could have buttons pointing to https://github.com/metakgp/mfqp and https://github.com/metakgp/mfqp-source. Right?

**Comment by icyflame** [comment]
Hey @kaustubhhiware, this looks good and has been open for quite a while. I will merge this in a few hours, preview looks good on desktop and mobile.

cc @athityakumar @ghostwriternr @DefCon-007 @nishnik

**Comment by kaustubhhiware** [comment]
@icyflame :+1: 
@athityakumar I feel the button thing would go against the minimal look of the website. Please see the preview [here](http://cse.iitkgp.ac.in/~hknarendra/metakgp/). I think the button size could occupy a significant portion of smaller screens. What do you think ?

**Comment by athityakumar** [comment]
@kaustubhhiware - Hmm, how about a simple link then? Just for the benefit of developers who might want to contribute / get started with open-source.

**Pull request merged**
